apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-1
  labels:
    app: postgres-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-1
  template:
    metadata:
      labels:
        service: postgres-1
        app: postgres-1
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db0
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres-1"
      volumes:
        - persistentVolumeClaim:
            claimName: postgres-1
          name: postgres-1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    service: postgres-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-1
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
